'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.33440
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FakeSteam.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bg_BG_CreateAccount() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_BG_CreateAccount", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bg_BG_ErrorDialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_BG_ErrorDialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bg_BG_Main() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_BG_Main", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Вход в Steam.
        '''</summary>
        Friend ReadOnly Property bg_BG_Title() As String
            Get
                Return ResourceManager.GetString("bg_BG_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cs_CZ_CreateAccount() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cs_CZ_CreateAccount", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cs_CZ_ErrorDialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cs_CZ_ErrorDialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cs_CZ_Main() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cs_CZ_Main", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Přihlášení ke službě Steam.
        '''</summary>
        Friend ReadOnly Property cs_CZ_Title() As String
            Get
                Return ResourceManager.GetString("cs_CZ_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property da_DK_CreateAccount() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("da_DK_CreateAccount", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property da_DK_ErrorDialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("da_DK_ErrorDialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property da_DK_Main() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("da_DK_Main", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Steam-logon.
        '''</summary>
        Friend ReadOnly Property da_DK_Title() As String
            Get
                Return ResourceManager.GetString("da_DK_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property de_DE_CreateAccount() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("de_DE_CreateAccount", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property de_DE_ErrorDialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("de_DE_ErrorDialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property de_DE_Main() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("de_DE_Main", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Steam-Login.
        '''</summary>
        Friend ReadOnly Property de_DE_Title() As String
            Get
                Return ResourceManager.GetString("de_DE_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property el_GR_CreateAccount() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("el_GR_CreateAccount", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property el_GR_ErrorDialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("el_GR_ErrorDialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property el_GR_Main() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("el_GR_Main", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Είσοδος στο Steam.
        '''</summary>
        Friend ReadOnly Property el_GR_Title() As String
            Get
                Return ResourceManager.GetString("el_GR_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property en_US_CreateAccount() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("en_US_CreateAccount", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property en_US_ErrorDialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("en_US_ErrorDialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property en_US_Main() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("en_US_Main", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Steam.
        '''</summary>
        Friend ReadOnly Property en_US_Title() As String
            Get
                Return ResourceManager.GetString("en_US_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property es_ES_CreateAccount() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("es_ES_CreateAccount", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property es_ES_ErrorDialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("es_ES_ErrorDialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property es_ES_Main() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("es_ES_Main", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inicio de sesión en Steam.
        '''</summary>
        Friend ReadOnly Property es_ES_Title() As String
            Get
                Return ResourceManager.GetString("es_ES_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fi_FI_CreateAccount() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fi_FI_CreateAccount", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fi_FI_ErrorDialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fi_FI_ErrorDialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fi_FI_Main() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fi_FI_Main", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Steam-kirjautuminen.
        '''</summary>
        Friend ReadOnly Property fi_FI_Title() As String
            Get
                Return ResourceManager.GetString("fi_FI_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fr_FR_CreateAccount() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fr_FR_CreateAccount", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fr_FR_ErrorDialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fr_FR_ErrorDialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fr_FR_Main() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fr_FR_Main", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connexion à Steam.
        '''</summary>
        Friend ReadOnly Property fr_FR_Title() As String
            Get
                Return ResourceManager.GetString("fr_FR_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hu_HU_CreateAccount() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hu_HU_CreateAccount", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hu_HU_ErrorDialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hu_HU_ErrorDialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hu_HU_Main() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hu_HU_Main", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Steam bejelentkezés.
        '''</summary>
        Friend ReadOnly Property hu_HU_Title() As String
            Get
                Return ResourceManager.GetString("hu_HU_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property it_IT_CreateAccount() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("it_IT_CreateAccount", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property it_IT_ErrorDialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("it_IT_ErrorDialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property it_IT_Main() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("it_IT_Main", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Accesso a Steam.
        '''</summary>
        Friend ReadOnly Property it_IT_Title() As String
            Get
                Return ResourceManager.GetString("it_IT_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nl_NL_CreateAccount() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nl_NL_CreateAccount", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nl_NL_ErrorDialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nl_NL_ErrorDialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nl_NL_Main() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nl_NL_Main", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inloggen bij Steam.
        '''</summary>
        Friend ReadOnly Property nl_NL_Title() As String
            Get
                Return ResourceManager.GetString("nl_NL_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nn_NO_CreateAccount() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nn_NO_CreateAccount", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nn_NO_ErrorDialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nn_NO_ErrorDialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nn_NO_Main() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nn_NO_Main", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pålogging – Steam.
        '''</summary>
        Friend ReadOnly Property nn_NO_Title() As String
            Get
                Return ResourceManager.GetString("nn_NO_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pl_PL_CreateAccount() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pl_PL_CreateAccount", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pl_PL_ErrorDialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pl_PL_ErrorDialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pl_PL_Main() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pl_PL_Main", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Logowanie do Steam.
        '''</summary>
        Friend ReadOnly Property pl_PL_Title() As String
            Get
                Return ResourceManager.GetString("pl_PL_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pt_BR_CreateAccount() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pt_BR_CreateAccount", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pt_BR_ErrorDialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pt_BR_ErrorDialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pt_BR_Main() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pt_BR_Main", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Iniciar sessão no Steam.
        '''</summary>
        Friend ReadOnly Property pt_BR_Title() As String
            Get
                Return ResourceManager.GetString("pt_BR_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pt_PT_CreateAccount() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pt_PT_CreateAccount", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pt_PT_ErrorDialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pt_PT_ErrorDialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pt_PT_Main() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pt_PT_Main", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Iniciar sessão no Steam.
        '''</summary>
        Friend ReadOnly Property pt_PT_Title() As String
            Get
                Return ResourceManager.GetString("pt_PT_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ro_RO_CreateAccount() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ro_RO_CreateAccount", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ro_RO_ErrorDialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ro_RO_ErrorDialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ro_RO_Main() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ro_RO_Main", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Вхід до Steam.
        '''</summary>
        Friend ReadOnly Property ro_RO_Title() As String
            Get
                Return ResourceManager.GetString("ro_RO_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ru_RU_CreateAccount() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ru_RU_CreateAccount", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ru_RU_ErrorDialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ru_RU_ErrorDialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ru_RU_Main() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ru_RU_Main", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Вход в Steam.
        '''</summary>
        Friend ReadOnly Property ru_RU_Title() As String
            Get
                Return ResourceManager.GetString("ru_RU_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property SteamApp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("SteamApp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property SteamInstaller() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("SteamInstaller", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sv_SE_CreateAccount() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sv_SE_CreateAccount", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sv_SE_ErrorDialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sv_SE_ErrorDialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sv_SE_Main() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sv_SE_Main", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Logga in – Steam.
        '''</summary>
        Friend ReadOnly Property sv_SE_Title() As String
            Get
                Return ResourceManager.GetString("sv_SE_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property th_TH_CreateAccount() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("th_TH_CreateAccount", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property th_TH_ErrorDialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("th_TH_ErrorDialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property th_TH_Main() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("th_TH_Main", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to เข้าสู่ระบบ Steam.
        '''</summary>
        Friend ReadOnly Property th_TH_Title() As String
            Get
                Return ResourceManager.GetString("th_TH_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tr_TR_CreateAccount() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tr_TR_CreateAccount", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tr_TR_ErrorDialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tr_TR_ErrorDialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tr_TR_Main() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tr_TR_Main", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Steam Girişi.
        '''</summary>
        Friend ReadOnly Property tr_TR_Title() As String
            Get
                Return ResourceManager.GetString("tr_TR_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property uk_UA_CreateAccount() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("uk_UA_CreateAccount", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property uk_UA_ErrorDialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("uk_UA_ErrorDialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property uk_UA_Main() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("uk_UA_Main", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Autentificare Steam.
        '''</summary>
        Friend ReadOnly Property uk_UA_Title() As String
            Get
                Return ResourceManager.GetString("uk_UA_Title", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
